default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: blog_development
  username: postgres
  password: root
  host: localhost
  port: 5432

test:
  <<: *default
  database: blog_test
  username: postgres
  password: root
  host: localhost
  port: 5432

production:
  <<: *default
  database: blog
